export const menu = [  
  {
    id: 1,
    url: "/images/aos.png",
    weight: "450 мл",
    title:"AOS средство для мытья посуды Crystal",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: AOS",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: AOS",
    price: 48,
    for: "Средства для мытья посуды"
  },
  {
    id: 2,
    url: "/images/ariel.png",
    weight: "15X28.8 г.",
    title: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Ariel",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Ariel",
    price: 120,
    for: "Средства для стирки"
  },
  {
    id: 3,
    url: "/images/bi-max.png",
    weight: "1500 г",
    title: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Bi-max",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Bi-max",
    price: 115,
    for: "Средства для стирки"
  },
  {
    id: 4,
    url: "/images/sorti.png",
    weight: "450 мл",
    title:"SORTI средство для мытья посуды Crystal",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Sorti",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Sorti",
    price: 95,
    for: "Средства для мытья посуды"
  },
  {
    id: 5,
    url: "/images/bioMio.png",
    weight: "90 г.",
    title: "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: BioMio",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: BioMio",
    price: 24,
    for: "Уход за руками"
  },
  {
    id: 6,
    url: "/images/shampoo.png",
    weight: "450 мл",
    title:"Шампунь для всех типов волос",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Head&Shoulders",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Head&Shoulders",
    price: 180,
    for: "Уход за волосами"
  },
  {
    id: 7,
    url: "/images/gel.png",
    weight: "15X28.8 г.",
    title: "Гель для душа",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Old Spice",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Old Spice",
    price: 148,
    for: "Уход за телом"
  },
  {
    id: 8,
    url: "/images/boro.png",
    weight: "1500 г",
    title: "Boro plus крем для рук",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Boro+",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Boro+",
    price: 32,
    for: "Уход за руками"
  },
  {
    id: 9,
    url: "/images/foot.png",
    weight: "450 мл",
    title:"Крем для ног",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Gerlachs",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Gerlachs",
    price: 54,
    for: "Уход за ногами"
  },
  {
    id: 10,
    url: "/images/face.png",
    weight: "90 г.",
    title: "Крем для лица",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: L Oreal",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: L Oreal",
    price: 86,
    for: "Уход за лицом"
  },
  {
    id: 11,
    url: "/images/sun.png",
    weight: "450 мл",
    title:"Средство для загара",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Emerald bay",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Emerald",
    price: 75,
    for: "Средства для загара"
  },
  {
    id: 12,
    url: "/images/shave.png",
    weight: "15X28.8 г.",
    title: "Крем для бритья",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Viking",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Viking",
    price: 45,
    for: "Средства для бритья"
  },
  {
    id: 13,
    url: "/images/gift.png",
    weight: "1500 г",
    title: "Подарочный набор для женщин",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Medolobov",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Medolobov",
    price: 250,
    for: "Подарочные наборы"
  },
  {
    id: 14,
    url: "/images/splat.png",
    weight: "450 мл",
    title:"Зубная паста",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Splat",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Splat",
    price: 91,
    for: "Гигиена полости рта"
  },
  {
    id: 15,
    url: "/images/paper.png",
    weight: "90 г.",
    title: "Туалетная бумага",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Нэфис",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Нэфис",
    price: 20,
    for: "Бумажная продукция"
  },
  {
    id: 16,
    url: "/images/mustang.png",
    weight: "90 г.",
    title: "Расчёстка для волос",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Mustang",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Mustang",
    price: 147,
    for: "Уход за волосами"
  },
  {
    id: 17,
    url: "/images/boker.png",
    weight: "90 г.",
    title: "Опасная бритва",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Boker",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Boker",
    price: 850,
    for: "Средства для бритья"
  },
  {
    id: 18,
    url: "/images/colgate.png",
    weight: "90 г.",
    title: "Зубная паста",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Colgate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Colgate",
    price: 48.76,
    for: "Гигиена полости рта"
  },
  {
    id: 19,
    url: "/images/colgatesh.png",
    weight: "90 г.",
    title: "Зубная щётка",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Colgate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Colgate",
    price: 120,
    for: "Гигиена полости рта"
  },
  {
    id: 20,
    url: "/images/desodorant.png",
    weight: "90 г.",
    title: "Дезодорант для мужчин",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Нэфис",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Нэфис",
    price: 300,
    for: "Гигиеническая продукция"
  },
  {
    id: 21,
    url: "/images/unis.png",
    weight: "90 г.",
    title: "Салфетки гигиенические, влажные",
    code: "Штрихкод: 4604049097548",
    manufacturer: "Производитель: Unis",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
    brand: "Бренд: Unis",
    price: 35,
    for: "Гигиеническая продукция"
  },
]